title: Data Management Plan Training
author: Bjørn Peare Bartholdy
format: 
    revealjs:
        navigation-mode: vertical
        incremental: true
        #center: true
        logo: img/TUDelft_logo_rgb.png
        title-slide-attributes:
          data-background-color: "#00A6D6"
          data-background-image: "img/TUDelft_logo_white.png"
          data-background-position: "0% 110%"
          data-background-size: "30%"
        #css: delft-theme.css
        theme: [default, tud-theme.scss]
        #preview-links: true